version: "3.9"
services:
  fastapi_app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/src
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./src/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - fastapi_app

volumes:
  postgres_data: